baseURL: "https://mfokeefe.github.io/" 
languageCode: "en-us"
title: "Matthew O'Keefe"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Contact
          url: mailto:matthew.okeefe@vanderbilt.edu
          weight: 1
        - name: Download CV
          url: "/cv.pdf"
          weight: 2
        - name: Bio
          url: "https://as.vanderbilt.edu/economics/bio/matthew-okeefe/" #/research
          weight: 3



params:
    description: "Hello world."
    author:
    # googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: false # true
          title: Matthew O'Keefe
          subtitle: "Assistant Professor of Economics, Vanderbilt University. <br><br> I am an industrial organization economist interested in energy, power markets, and the environment. I recently received a PhD in Economics from Northwestern University.<br><br>Email: <a href='mailto:matthew.okeefe@vanderbilt.edu'>matthew.okeefe@vanderbilt.edu</a> <br>"
          imageUrl: "images/photo.jpg"
          imageWidth: 120
          imageHeight: 180
          imageTitle: Matt
          buttons:
            # - name: Home
            #   url: ""
            - name: Research
              url: research/
            - name: Download CV
              url: /cv.pdf
            - name: Contact
              url: mailto:matthew.okeefe@vanderbilt.edu
            # - name: Job Market Site
            # url: https://sites.northwestern.edu/mfo275/
    socialIcons:
        # - name: CV
        #   url: /cv.pdf
        # - name: Contact
        #   url: mailto:matthewokeefe2023@u.northwestern.edu

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      # text: "Matthew O'Keefe"
      # icon: /favicon.ico
      # iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
